### ISSUE TITLE
Not recognizing unsupported gap property in context of flex box

### ISSUE THREAD

**Issue by dakur** [anandthakker/doiuse#144]
`gap` together with `display: flex` is supported much later than within `display: grid`.

For example for `safari <= 14.1`, it should raise a warning on `display: flex` + `gap`

**Comment by WebMechanic** [comment]
> It would be very nice to have this detection.

@sven-meyer-wetter-com and then what? 
if you want to keep the style (likely) you still need to provide a fallback for the flex items using offset margins.

This is best and easily detectable at runtime in the browser anyway and the html/body element can be tagged with that infomation. all you need is a "no-flexgap" selector to compensate.

```js
/* run after DOMContentLoaded, via script module, or deferred script */
function checkFlexGap() {
  const ROOT = document.body; // or document.documentElement
  const flx = ROOT.appendChild(document.createElement('ruby'));
  flx.style.display = 'flex';
  flx.style.flexDirection = 'column';
  flx.style.rowGap = '1px';
  flx.appendChild(document.createElement('div'));
  flx.appendChild(document.createElement('div'));
  if (flx.scrollHeight !== 1) ROOT.classList.add('no-flexgap');
  // console.debug(flx.scrollHeight, flx.style.cssText);
  // flx.style.cssText = '';
  // ROOT.removeChild(flx);
}
checkFlexGap();
```
```css
.flexed { display:flex; flex-wrap:wrap; gap:1ch; }
html.no-flexgap {
  .flexed > :first-child { .. adjust margins.. }
  .flexed > .items { .. adjust margins.. }
  .flexed > :last-child { .. adjust margins.. }
}
```
(based on [the Modernizr flex gap test](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/flexgap.js))
