### ISSUE TITLE
`viewport-unit-variants` false positive with data-url

### ISSUE THREAD

**Issue by edg2s** [anandthakker/doiuse#183]
When a data-url contains a string that looks like a number and unit, the rule triggers:
Example code:
```css
span {
  background-image: url( data:image/svg+xml;base64,..............5vb............ );
}
```
