### ISSUE TITLE
css-not-sel-list doesn't support [class*='xxx'] syntax

### ISSUE THREAD

**Issue by acailly** [anandthakker/doiuse#194]
I use stylelint with the plugin no-unsupported-browser-features, that uses doiuse internally

Stylelint report an error `Unexpected browser feature "css-not-sel-list" is not not supported by ...` with the following code: 

```scss
&:not([class*='foo-bar']) {
  box-shadow: none;
}
```

I see on https://caniuse.com/css-not-sel-list that `:not([c])` should be supported, right?
Or maybe I'm missing something 😄
