### ISSUE TITLE
False positive on transition: grid and transition: grid-*

### ISSUE THREAD

**Issue by yassh** [anandthakker/doiuse#197]
Unlike the  [Can I use database](https://caniuse.com/?search=css-grid-animation), doiuse warns against the usage of `transition: grid` and `transition: grid-*` like this:

```
main.css:2:1: CSS Grid animation not supported by: Edge (129,130), Chrome (129,130), Chrome for Android (129) (css-grid-animation)
main.css:3:1: CSS Grid animation not supported by: Edge (129,130), Chrome (129,130), Chrome for Android (129) (css-grid-animation)
main.css:4:1: CSS Grid animation not supported by: Edge (129,130), Chrome (129,130), Chrome for Android (129) (css-grid-animation)
main.css:5:1: CSS Grid animation not supported by: Edge (129,130), Chrome (129,130), Chrome for Android (129) (css-grid-animation)
main.css:7:1: CSS Grid animation not supported by: Edge (129,130), Chrome (129,130), Chrome for Android (129) (css-grid-animation)
main.css:8:1: CSS Grid animation not supported by: Edge (129,130), Chrome (129,130), Chrome for Android (129) (css-grid-animation)
main.css:9:1: CSS Grid animation not supported by: Edge (129,130), Chrome (129,130), Chrome for Android (129) (css-grid-animation)
```

main.css:

```css
.test {
  transition: grid 1s;
  transition: grid-template 1s;
  transition: grid-template-rows 1s;
  transition: grid-template-columns 1s;

  transition: grid-template-areas 1s;
  transition: grid-auto-rows 1s;
  transition: grid-auto-columns 1s;
}
```
