### ISSUE TITLE
rem unit not supported but fallback provided

### ISSUE THREAD

**Issue by sebastienbarre** [anandthakker/doiuse#23]
I'm using the [pixrem](https://github.com/robwierzbowski/node-pixrem) PostCSS plugin, which transforms this: 
```css
.sky {
  margin: 2.5rem 2px 3em 100%;
}
```
into this:
```css
.sky {
  margin: 80px 2px 3em 100%;
  margin: 2.5rem 2px 3em 100%;
}
```
Unfortunately, `doiuse` still reports an error, I assume it's not noticing a fallback was provided and choking on the second rule?
```
rem (root em) units not supported by: IE (8,9,10)
```
Thanks
