### ISSUE TITLE
Feature: Ignore rules covered by feature query

### ISSUE THREAD

**Issue by Dyljyn** [anandthakker/doiuse#78]
I would love for the linter to ignore CSS rules that are covered already by feature queries, instead of having to ignore them manually, like this:

```css
@supports (position: sticky) {
  /* doiuse-disable css-sticky */
  .mti-sticky {
    position: sticky;
  }
  /* doiuse-enable css-sticky */
}
```
